echo Packing...
nuget pack -OutputDirectory ..\publish -NonInteractive
echo Pushing...
nuget push ..\publish\CipherPark.AuroraEngine.0.0.1.nupkg oy2msk4qrtfka44estrqaeaqbkxt5w3e5ipe5yj57hom4e -Source https://api.nuget.org/v3/index.json